## Banco de dados
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

## Sonar
sonar.secret.key=${SONAR_SECRET_KEY}
sonar.base.url.frontend=${SONAR_BASE_URL_FRONTEND}

#AWS Credentials
spring.cloud.aws.credentials.access-key=${AWS_ACCESS_KEY_ID}
spring.cloud.aws.credentials.secret-key=${AWS_SECRET_ACCESS_KEY}
spring.cloud.aws.region.static=us-east-1

## AWS S3
aws.s3.endpoint=${AWS_S3_ENDPOINT}
aws.s3.bucket.sonar-audio=${AWS_S3_BUCKET_NAME}

## OpenAI
openai.api.url=${OPENAI_API_URL}
openai.api.key=${OPENAI_API_KEY}

## AssemblyAI
assemblyai.api.key=${ASSEMBLYAI_API_KEY}
api.url.transcript=${ASSEMBLYAI_API_URL}
assemblyai.webhook.url=${ASSEMBLYAI_WEBHOOK_URL}
