assemblyai.webhook.url=${ASSEMBLYAI_WEBHOOK_URL}
openai.api.key=${OPENAI_API_KEY}
sonar.secret.key=${SONAR_SECRET_KEY}
sonar.base.url.frontend=${SONAR_BASE_URL_FRONTEND}
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
